version: 2

updates:
  - package-ecosystem: "npm"
    directories:
      - "/**"
    exclude-paths:
      - "submodules/**"
    schedule:
      interval: "cron"
      cronjob: "0 3 1,15 * *"
      time: "03:00"
      timezone: "Europe/London"
    cooldown:
      default-days: 7
    labels:
      - dependabot
      - dependencies
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
      # We have to ignore those two packages and update them manually.
      # This is because they are hosted on a private registry, but configuring
      # dependabot to use the private registry and fallback to NPM when a
      # package isn't found on the private registry doesn't work for pacakges
      # prefixed with @govuk-one-login/ which are on NPM and not the private
      # registry (e.g. @govuk-one-login/frontend-ui). Because @govuk-one-login/
      # is also the GitHub org name dependabot seems to assume that all
      # @govuk-one-login/ prefixed packages are on the private registry
      # and when it can't find one there it doesn't check NPM it just errors.
      # This occurs even when replaces-base is set to false in the dependabot
      # registry config. This leaves us with two options: leave the private registry
      # configured which means that packages on the private registry will receive
      # updates and packages on NPM will receive updates as long as they aren't
      # prefixed with @govuk-one-login/, or don't configure the private registry
      # which means that all packages on NPM will receive updates but packages on
      # the private registry won't. I've gone for option 2 because we really only
      # need to update the event-catalogue private packages when adding new events
      # and we can do that at the same time as implementing the events in code.
      - dependency-name: "@govuk-one-login/event-catalogue"
      - dependency-name: "@govuk-one-login/event-catalogue-schemas"
    commit-message:
      prefix: BAU
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directories:
      - "/"
    schedule:
      interval: "cron"
      cronjob: "0 3 1,15 * *"
      time: "03:00"
      timezone: "Europe/London"
    cooldown:
      default-days: 7
    labels:
      - dependabot
      - dependencies
    commit-message:
      prefix: BAU
    groups:
      github-actions-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pre-commit"
    directories:
      - "/"
    schedule:
      interval: "cron"
      cronjob: "0 3 1,15 * *"
      time: "03:00"
      timezone: "Europe/London"
    cooldown:
      default-days: 7
    labels:
      - dependabot
      - dependencies
    commit-message:
      prefix: BAU

  - package-ecosystem: "terraform"
    directories:
      - "/solutions/infra"
    schedule:
      interval: "cron"
      cronjob: "0 3 1,15 * *"
      time: "03:00"
      timezone: "Europe/London"
    cooldown:
      default-days: 7
    labels:
      - dependabot
      - dependencies
    commit-message:
      prefix: BAU

  - package-ecosystem: docker
    directories:
      - "/solutions/integration-tests"
      - "/solutions/localstack/local-kms"
      - "/solutions/localstack/localstack"
    schedule:
      interval: "cron"
      cronjob: "0 3 1,15 * *"
      time: "03:00"
      timezone: "Europe/London"
    cooldown:
      default-days: 7
    labels:
      - dependabot
      - dependencies
    commit-message:
      prefix: BAU
    ignore:
      - dependency-name: "node"
        update-types:
          - "version-update:semver-major"
      # Can't be updated past the current major & minor version due
      # to localstack changing the licence
      - dependency-name: "localstack/localstack"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: "gitsubmodule" # zizmor: ignore[dependabot-cooldown]
    directories:
      - "/"
    schedule:
      interval: daily
      time: "03:00"
      timezone: "Europe/London"
    labels:
      - dependabot
      - dependencies
    commit-message:
      prefix: BAU

  - package-ecosystem: pip
    directories:
      - "/**"
    exclude-paths:
      - "submodules/**"
    schedule:
      interval: "cron"
      cronjob: "0 3 1,15 * *"
      time: "03:00"
      timezone: "Europe/London"
    cooldown:
      default-days: 7
    labels:
      - dependabot
      - dependencies
