AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Account management smoke tests

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs24.x

Resources:
  SmokeTestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/canary.handler
      CodeUri: .
